version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-http2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certificates:/etc/nginx/certificates
      - ./site:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    command: [nginx-debug, '-g', 'daemon off;']